language: php

php:
  - 5.5
  - 5.6
  - hhvm

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;'